In [30]:
##NUMPY
# Question: 1) Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
import numpy as np

# From creating a custom array from list
A = np.array([1,2,3,4,5])
B = np.array([4,5,6,7,8])

vertical_stack = np.vstack([A,B])
horizontal_stack = np.hstack([A,B])
print(horizontal_stack)
print(vertical_stack)

[1 2 3 4 5 4 5 6 7 8]
[[1 2 3 4 5]
 [4 5 6 7 8]]


In [31]:
## NUMPY
# Question: 2) Find common elements between A and B. [Hint : Intersection of two sets]
common_element = np.intersect1d(A,B)
print(common_element)


[4 5]


In [40]:
## NUMPY
# Question: 3) Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
within_range = np.where((A >= 5) & (A < 10))
print("Index: ", within_range)
print("Value: ", A[within_range])

Index:  (array([4]),)
Value:  [5]


In [50]:
## NUMPY
# Question: 4) Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

import numpy as np
from sklearn.datasets import load_iris

# load numeric features only (150 x 4)
iris = load_iris()
iris_2d = iris.data  # columns: [sepal_length, sepal_width, petal_length, petal_width]

# Filter: petal_length (col 2) > 1.5 and sepal_length (col 0) < 5.0
mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered_rows = iris_2d[mask]

print(filtered_rows[:5])
print("Rows matched:", filtered_rows.shape[0])


[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]]
Rows matched: 6


In [54]:
## PANDAS
# Question: 1) From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.head())
resulting_row = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(resulting_row)

  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0     

In [61]:
## PANDAS
# Question: 2) Replace missing values in Min.Price and Max.Price columns with their respective mean.

min_mean = df['Min.Price'].mean()
max_mean = df['Max.Price'].mean()

# replace with NaN of max price and min price to the column mean
df['Min.Price'].fillna(min_mean, inplace = True)
df['Max.Price'].fillna(max_mean, inplace = True)

print(df[['Min.Price','Max.Price']].head())








   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [65]:
## PANDAS
# Question: 3) How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

print(df.head())

filtered_rows = df[df.sum(axis = 1) > 100]
print(filtered_rows)

    0   1   2   3
0  20  36  10  28
1  30  25  31  39
2  38  11  37  15
3  25  15  39  17
4  12  16  14  26
     0   1   2   3
1   30  25  31  39
2   38  11  37  15
5   38  37  33  11
6   32  31  16  35
7   36  35  27  11
10  37  28  18  21
11  27  34  31  23
13  21  33  30  19
